# Generated by Django 5.2.1 on 2025-05-19 16:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='Kategori Titel')),
                ('purpose', models.CharField(blank=True, max_length=400)),
                ('help_text', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IotDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=63, unique=True, verbose_name='Enhed Navn')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.category')),
            ],
            options={
                'verbose_name': 'IoT Device',
                'verbose_name_plural': 'IoT Devices',
                'db_table': 'iot_device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Program Navn')),
                ('duration', models.DurationField()),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='device.category')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'program',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActiveProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('iot_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_programs', to='device.iotdevice')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.program')),
            ],
            options={
                'verbose_name': 'Active Program',
                'verbose_name_plural': 'Active Programs',
                'db_table': 'active_program',
                'ordering': ['-start_time'],
                'managed': True,
            },
        ),
    ]
