# Generated by Django 5.2.1 on 2025-05-21 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeprogram',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 14, 29, 30, 651097, tzinfo=datetime.timezone.utc)),
        ),
    ]
