# Generated by Django 5.2.1 on 2025-05-19 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeprogram',
            options={'managed': True, 'ordering': ['-start_time'], 'verbose_name': 'Active Program', 'verbose_name_plural': 'Active Programs'},
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='active_programs',
        ),
        migrations.AlterField(
            model_name='activeprogram',
            name='iot_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_programs', to='device.iotdevice'),
        ),
        migrations.AlterField(
            model_name='activeprogram',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='hostname',
            field=models.CharField(max_length=63, unique=True, verbose_name='Enhed Navn'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.DurationField(),
        ),
    ]
