# Generated by Django 5.2.1 on 2025-05-21 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_activeprogram_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeprogram',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
